# Generated by Django 3.2.7 on 2021-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default='provide caption', max_length=100),
        ),
    ]
