# Generated by Django 3.2.7 on 2021-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0002_auto_20210909_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('branch', models.TextField()),
                ('usn', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
